const PROJECTS = [
  { id: 'minutes', title: 'Make Your Minutes Matter', type: 'Web Design · Branding',
    pages: 14, imgDir: 'project-images/minutes',
    cover: 'project-images/minutes/cover.webp',
    behance: 'https://www.behance.net/gallery/241613333/Make-Your-Minutes-Matter-Campaign',
    color: '#A68B7B', accent: '#8B5CF6' },
  { id: 'heimasana', title: 'Heimasana', type: 'Branding',
    pages: 13, imgDir: 'project-images/heimasana',
    cover: 'project-images/heimasana/cover.webp',
    behance: 'https://www.behance.net/gallery/219210061/Heimasana-Branding',
    color: '#7BA68B', accent: '#0D9488' },
  { id: 'montessori', title: 'Montessori', type: 'Web Design · Branding',
    pages: 6, imgDir: 'project-images/montessori',
    cover: 'project-images/montessori/cover.webp',
    behance: 'https://www.behance.net/gallery/226546243/Montessori-Visual-Identity-and-Web-Design',
    color: '#8BA67B', accent: '#34D399' },
  { id: 'ecostitch', title: 'Eco-Stitch', type: 'Branding · Campaign',
    pages: 7, imgDir: 'project-images/ecostitch',
    cover: 'project-images/ecostitch/cover.webp',
    behance: 'https://www.behance.net/gallery/214965103/Eco-Stitch-Sustainable-Design',
    color: '#6B8B6E', accent: '#0D9488' },
  { id: 'volte', title: 'VOLTE!', type: 'Campaign',
    pages: 4, imgDir: 'project-images/volte',
    cover: 'project-images/volte/cover.webp',
    behance: 'https://www.behance.net/gallery/226549245/VOLTE-Postcard-Campaign-Design',
    color: '#8B7B6B', accent: '#FB923C' },
  { id: 'sublimeppc', title: 'Sublimeppc', type: 'Web Design · Branding',
    pages: 9, imgDir: 'project-images/sublimeppc',
    cover: 'project-images/sublimeppc/cover.webp',
    behance: 'https://www.behance.net/gallery/221729969/Sublimeppc-website-branding',
    color: '#727D8B', accent: '#60A5FA' },
  { id: 'sitotiskem', title: 'Sítotiskem', type: 'Branding',
    pages: 13, imgDir: 'project-images/sitotiskem',
    cover: 'project-images/sitotiskem/cover.webp',
    behance: 'https://www.behance.net/gallery/216702231/Sitotiskem-Branding',
    color: '#C4A882', accent: '#E8449A' },
  { id: 'mealmate', title: 'MealMate', type: 'App Design',
    pages: 16, imgDir: 'project-images/mealmate',
    cover: 'project-images/mealmate/cover.webp',
    behance: 'https://www.behance.net/gallery/226257221/MealMate-Application',
    color: '#7BA67B', accent: '#34D399' },
  { id: 'bookcover', title: 'Book Covers', type: 'Editorial',
    pages: 4, imgDir: 'project-images/bookcover',
    cover: 'project-images/bookcover/cover.webp',
    behance: 'https://www.behance.net/gallery/211649451/Book-cover-design',
    color: '#8B7D72', accent: '#E8449A' },
  { id: 'greyaway', title: 'Grey Away', type: 'Branding',
    pages: 13, imgDir: 'project-images/greyaway',
    cover: 'project-images/greyaway/cover.webp',
    behance: 'https://www.behance.net/gallery/215630899/Grey-Away-Branding',
    color: '#7B7D8B', accent: '#8B5CF6' },
];
window.PROJECTS = PROJECTS;
